repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo03
repo_name: 2025.2-Grupo03
site_name: Grupo 03 - Requisitos de Software (2025.2)
site_url: https://requisitos-de-software.github.io/2025.2-Grupo03/

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: blue
      accent: light blue
      background: "#f5f7fa"
      text: "#22272e"
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: blue grey
      accent: cyan
      background: "#22272e"
      text: "#f5f7fa"

markdown_extensions:
  - attr_list
  - tables

nav:
  - Home: index.md
  - Atas: 
    - Ata 09/09/2025 1: Atas/ata09-09-2025_1.md
    - Ata 09/09/2025 2: Atas/ata09-09-2025_2.md
    - Ata 10/09/2025: Atas/ata10-09-2025.md
    - Ata 18/09/2025: Atas/ata18-09-2025.md
  - Videos: Videos/videos.md
  - Apresentação: 
      - Introdução: Apresentação/apresentacao.md
      - Apresentação 1: Apresentação/apresentacao1.md
  - Planejamento: 
    - HeatMap: Planejamento/heatmap.md
    - Ferramentas: Planejamento/ferramentas.md
    - Cronograma planejado: Planejamento/cronograma_planejado.md
    - Cronograma executado: Planejamento/cronograma_executado.md
    - Aplicativos avaliados: Planejamento/Aplicativos.md
    - Aplicativo escolhido: Planejamento/aplicativo.md
  - Rich Picture: Rich-picture/richpicture.md
  - Verificação: 
    - Verificação 1: Verificacao/verificacao.md
    - Verificação 2: Verificacao/verificacao2.md
  - Elicitação:
    - Perfil de Usuário: Elicitacao/perfil_usuario.md
    - Requisitos Elicitados: Elicitacao/requisitos_elicitados.md
    - Tecnicas de Elicitação: 
      - Análise de Documentos: Elicitacao/analise_de_documentos.md
      - Entrevista: Elicitacao/entrevista.md
      - Brainstorming: Elicitacao/brainstorming.md
  - Inspeção:
    - Grupo: Inspeção/Inspeção_grupo.md
    - Grupo +1: Inspeção/inspeção_grupo_mais_um.md
